language: d
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y valgrind
script:
  - cd scripts
  - sh ./test.sh
  - sh ./compile.sh
  - cd ../tests
  - dmd ../lib/iz.a -I../import/ -run valgrinder.d